// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = DcoCodec,
    default_rust_opaque = RustOpaqueNom,
    default_rust_auto_opaque = RustAutoOpaqueNom,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 512408474;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__extract_name_from_db_impl(
    db_name: impl CstDecode<String>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "extract_name_from_db",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_db_name = db_name.cst_decode();
            transform_result_dco::<_, _, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::extract_name_from_db(api_db_name))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__generate_db_name_impl(
    name: impl CstDecode<String>,
    public_key_hex: impl CstDecode<String>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "generate_db_name",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_name = name.cst_decode();
            let api_public_key_hex = public_key_hex.cst_decode();
            transform_result_dco::<_, _, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::generate_db_name(
                    api_name,
                    api_public_key_hex,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__generate_keypair_impl(
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "generate_keypair",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            transform_result_dco::<_, _, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::generate_keypair())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__get_data_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    db_name: impl CstDecode<String>,
    key: impl CstDecode<String>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_data",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_db_name = db_name.cst_decode();
            let api_key = key.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok = crate::api::get_data(api_db_name, api_key).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__get_node_info_impl() -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco
{
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_node_info",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            transform_result_dco::<_, _, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::get_node_info())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__get_node_status_impl(
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_node_status",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            transform_result_dco::<_, _, String>((move || {
                let output_ok = crate::api::get_node_status()?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__get_peers_impl() -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_peers",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            transform_result_dco::<_, _, String>((move || {
                let output_ok = crate::api::get_peers()?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__greet_impl(
    name: impl CstDecode<String>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "greet",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_name = name.cst_decode();
            transform_result_dco::<_, _, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::greet(api_name))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__init_logging_impl() -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco
{
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_logging",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            transform_result_dco::<_, _, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::init_logging();
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__is_node_running_impl(
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "is_node_running",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            transform_result_dco::<_, _, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::is_node_running())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__request_sync_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    since_timestamp: impl CstDecode<Option<i64>>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "request_sync",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_since_timestamp = since_timestamp.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok = crate::api::request_sync(api_since_timestamp).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__send_gossip_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    topic: impl CstDecode<String>,
    message: impl CstDecode<String>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "send_gossip",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_topic = topic.cst_decode();
            let api_message = message.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok = crate::api::send_gossip(api_topic, api_message).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__send_latency_request_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    peer_id: impl CstDecode<String>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "send_latency_request",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_peer_id = peer_id.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok = crate::api::send_latency_request(api_peer_id).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__sign_message_with_key_impl(
    secret_key_hex: impl CstDecode<String>,
    message: impl CstDecode<String>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "sign_message_with_key",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_secret_key_hex = secret_key_hex.cst_decode();
            let api_message = message.cst_decode();
            transform_result_dco::<_, _, String>((move || {
                let output_ok = crate::api::sign_message_with_key(api_secret_key_hex, api_message)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__start_node_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    data_dir: impl CstDecode<String>,
    wallet_secret_key: impl CstDecode<Option<String>>,
    bootstrap_peers: impl CstDecode<Vec<String>>,
    region: impl CstDecode<Option<String>>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_node",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_data_dir = data_dir.cst_decode();
            let api_wallet_secret_key = wallet_secret_key.cst_decode();
            let api_bootstrap_peers = bootstrap_peers.cst_decode();
            let api_region = region.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok = crate::api::start_node(
                            api_data_dir,
                            api_wallet_secret_key,
                            api_bootstrap_peers,
                            api_region,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__stop_node_impl(port_: flutter_rust_bridge::for_generated::MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "stop_node",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok = crate::api::stop_node().await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__store_data_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    db_name: impl CstDecode<String>,
    key: impl CstDecode<String>,
    value: impl CstDecode<Vec<u8>>,
    public_key: impl CstDecode<String>,
    signature: impl CstDecode<String>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "store_data",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_db_name = db_name.cst_decode();
            let api_key = key.cst_decode();
            let api_value = value.cst_decode();
            let api_public_key = public_key.cst_decode();
            let api_signature = signature.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok = crate::api::store_data(
                            api_db_name,
                            api_key,
                            api_value,
                            api_public_key,
                            api_signature,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__store_data_local_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    db_name: impl CstDecode<String>,
    key: impl CstDecode<String>,
    value: impl CstDecode<Vec<u8>>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "store_data_local",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_db_name = db_name.cst_decode();
            let api_key = key.cst_decode();
            let api_value = value.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok =
                            crate::api::store_data_local(api_db_name, api_key, api_value).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__validate_timestamp_impl(
    timestamp: impl CstDecode<i64>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "validate_timestamp",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_timestamp = timestamp.cst_decode();
            transform_result_dco::<_, _, String>((move || {
                let output_ok = crate::api::validate_timestamp(api_timestamp)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__verify_db_name_impl(
    db_name: impl CstDecode<String>,
    public_key_hex: impl CstDecode<String>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "verify_db_name",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_db_name = db_name.cst_decode();
            let api_public_key_hex = public_key_hex.cst_decode();
            transform_result_dco::<_, _, String>((move || {
                let output_ok = crate::api::verify_db_name(api_db_name, api_public_key_hex)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__verify_message_signature_impl(
    public_key_hex: impl CstDecode<String>,
    message: impl CstDecode<String>,
    signature_hex: impl CstDecode<String>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "verify_message_signature",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_public_key_hex = public_key_hex.cst_decode();
            let api_message = message.cst_decode();
            let api_signature_hex = signature_hex.cst_decode();
            transform_result_dco::<_, _, String>((move || {
                let output_ok = crate::api::verify_message_signature(
                    api_public_key_hex,
                    api_message,
                    api_signature_hex,
                )?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl CstDecode<bool> for bool {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> bool {
        self
    }
}
impl CstDecode<i64> for i64 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> i64 {
        self
    }
}
impl CstDecode<u32> for u32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u32 {
        self
    }
}
impl CstDecode<u64> for u64 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u64 {
        self
    }
}
impl CstDecode<u8> for u8 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u8 {
        self
    }
}
impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::KeyPairDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_publicKey = <String>::sse_decode(deserializer);
        let mut var_secretKey = <String>::sse_decode(deserializer);
        return crate::api::KeyPairDto {
            public_key: var_publicKey,
            secret_key: var_secretKey,
        };
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::PeerInfoDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::PeerInfoDto>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::NodeInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_nodeId = <String>::sse_decode(deserializer);
        let mut var_publicKey = <String>::sse_decode(deserializer);
        let mut var_isRunning = <bool>::sse_decode(deserializer);
        return crate::api::NodeInfo {
            node_id: var_nodeId,
            public_key: var_publicKey,
            is_running: var_isRunning,
        };
    }
}

impl SseDecode for crate::api::NodeStatusDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_isRunning = <bool>::sse_decode(deserializer);
        let mut var_nodeId = <Option<String>>::sse_decode(deserializer);
        let mut var_connectedPeers = <u32>::sse_decode(deserializer);
        let mut var_discoveredPeers = <u32>::sse_decode(deserializer);
        let mut var_uptimeSeconds = <u64>::sse_decode(deserializer);
        let mut var_gossipMessagesReceived = <u64>::sse_decode(deserializer);
        let mut var_storageSizeBytes = <u64>::sse_decode(deserializer);
        let mut var_totalKeys = <u64>::sse_decode(deserializer);
        let mut var_syncOperations = <u32>::sse_decode(deserializer);
        let mut var_latencyRequestsSent = <u64>::sse_decode(deserializer);
        let mut var_latencyResponsesReceived = <u64>::sse_decode(deserializer);
        return crate::api::NodeStatusDto {
            is_running: var_isRunning,
            node_id: var_nodeId,
            connected_peers: var_connectedPeers,
            discovered_peers: var_discoveredPeers,
            uptime_seconds: var_uptimeSeconds,
            gossip_messages_received: var_gossipMessagesReceived,
            storage_size_bytes: var_storageSizeBytes,
            total_keys: var_totalKeys,
            sync_operations: var_syncOperations,
            latency_requests_sent: var_latencyRequestsSent,
            latency_responses_received: var_latencyResponsesReceived,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::NodeInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::NodeInfo>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<Vec<u8>>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::PeerInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_nodeId = <String>::sse_decode(deserializer);
        let mut var_publicKey = <String>::sse_decode(deserializer);
        let mut var_address = <Option<String>>::sse_decode(deserializer);
        let mut var_region = <Option<String>>::sse_decode(deserializer);
        let mut var_version = <Option<String>>::sse_decode(deserializer);
        let mut var_latencyMs = <Option<u64>>::sse_decode(deserializer);
        let mut var_isMobile = <bool>::sse_decode(deserializer);
        return crate::api::PeerInfoDto {
            node_id: var_nodeId,
            public_key: var_publicKey,
            address: var_address,
            region: var_region,
            version: var_version,
            latency_ms: var_latencyMs,
            is_mobile: var_isMobile,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::KeyPairDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.public_key.into_into_dart().into_dart(),
            self.secret_key.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::KeyPairDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::KeyPairDto> for crate::api::KeyPairDto {
    fn into_into_dart(self) -> crate::api::KeyPairDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::NodeInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.node_id.into_into_dart().into_dart(),
            self.public_key.into_into_dart().into_dart(),
            self.is_running.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::NodeInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::NodeInfo> for crate::api::NodeInfo {
    fn into_into_dart(self) -> crate::api::NodeInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::NodeStatusDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.is_running.into_into_dart().into_dart(),
            self.node_id.into_into_dart().into_dart(),
            self.connected_peers.into_into_dart().into_dart(),
            self.discovered_peers.into_into_dart().into_dart(),
            self.uptime_seconds.into_into_dart().into_dart(),
            self.gossip_messages_received.into_into_dart().into_dart(),
            self.storage_size_bytes.into_into_dart().into_dart(),
            self.total_keys.into_into_dart().into_dart(),
            self.sync_operations.into_into_dart().into_dart(),
            self.latency_requests_sent.into_into_dart().into_dart(),
            self.latency_responses_received.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::NodeStatusDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::NodeStatusDto> for crate::api::NodeStatusDto {
    fn into_into_dart(self) -> crate::api::NodeStatusDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::PeerInfoDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.node_id.into_into_dart().into_dart(),
            self.public_key.into_into_dart().into_dart(),
            self.address.into_into_dart().into_dart(),
            self.region.into_into_dart().into_dart(),
            self.version.into_into_dart().into_dart(),
            self.latency_ms.into_into_dart().into_dart(),
            self.is_mobile.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::PeerInfoDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::PeerInfoDto> for crate::api::PeerInfoDto {
    fn into_into_dart(self) -> crate::api::PeerInfoDto {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::KeyPairDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.public_key, serializer);
        <String>::sse_encode(self.secret_key, serializer);
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::PeerInfoDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::PeerInfoDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::NodeInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.node_id, serializer);
        <String>::sse_encode(self.public_key, serializer);
        <bool>::sse_encode(self.is_running, serializer);
    }
}

impl SseEncode for crate::api::NodeStatusDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_running, serializer);
        <Option<String>>::sse_encode(self.node_id, serializer);
        <u32>::sse_encode(self.connected_peers, serializer);
        <u32>::sse_encode(self.discovered_peers, serializer);
        <u64>::sse_encode(self.uptime_seconds, serializer);
        <u64>::sse_encode(self.gossip_messages_received, serializer);
        <u64>::sse_encode(self.storage_size_bytes, serializer);
        <u64>::sse_encode(self.total_keys, serializer);
        <u32>::sse_encode(self.sync_operations, serializer);
        <u64>::sse_encode(self.latency_requests_sent, serializer);
        <u64>::sse_encode(self.latency_responses_received, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::NodeInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::NodeInfo>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <Vec<u8>>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::PeerInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.node_id, serializer);
        <String>::sse_encode(self.public_key, serializer);
        <Option<String>>::sse_encode(self.address, serializer);
        <Option<String>>::sse_encode(self.region, serializer);
        <Option<String>>::sse_encode(self.version, serializer);
        <Option<u64>>::sse_encode(self.latency_ms, serializer);
        <bool>::sse_encode(self.is_mobile, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    // Section: dart2rust

    impl CstDecode<String> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            let vec: Vec<u8> = self.cst_decode();
            String::from_utf8(vec).unwrap()
        }
    }
    impl CstDecode<i64> for *mut i64 {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> i64 {
            unsafe { *flutter_rust_bridge::for_generated::box_from_leak_ptr(self) }
        }
    }
    impl CstDecode<crate::api::NodeInfo> for *mut wire_cst_node_info {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::NodeInfo {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<crate::api::NodeInfo>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<u64> for *mut u64 {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u64 {
            unsafe { *flutter_rust_bridge::for_generated::box_from_leak_ptr(self) }
        }
    }
    impl CstDecode<crate::api::KeyPairDto> for wire_cst_key_pair_dto {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::KeyPairDto {
            crate::api::KeyPairDto {
                public_key: self.public_key.cst_decode(),
                secret_key: self.secret_key.cst_decode(),
            }
        }
    }
    impl CstDecode<Vec<String>> for *mut wire_cst_list_String {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<String> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<Vec<crate::api::PeerInfoDto>> for *mut wire_cst_list_peer_info_dto {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::PeerInfoDto> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_loose {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    impl CstDecode<crate::api::NodeInfo> for wire_cst_node_info {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::NodeInfo {
            crate::api::NodeInfo {
                node_id: self.node_id.cst_decode(),
                public_key: self.public_key.cst_decode(),
                is_running: self.is_running.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::NodeStatusDto> for wire_cst_node_status_dto {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::NodeStatusDto {
            crate::api::NodeStatusDto {
                is_running: self.is_running.cst_decode(),
                node_id: self.node_id.cst_decode(),
                connected_peers: self.connected_peers.cst_decode(),
                discovered_peers: self.discovered_peers.cst_decode(),
                uptime_seconds: self.uptime_seconds.cst_decode(),
                gossip_messages_received: self.gossip_messages_received.cst_decode(),
                storage_size_bytes: self.storage_size_bytes.cst_decode(),
                total_keys: self.total_keys.cst_decode(),
                sync_operations: self.sync_operations.cst_decode(),
                latency_requests_sent: self.latency_requests_sent.cst_decode(),
                latency_responses_received: self.latency_responses_received.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::PeerInfoDto> for wire_cst_peer_info_dto {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::PeerInfoDto {
            crate::api::PeerInfoDto {
                node_id: self.node_id.cst_decode(),
                public_key: self.public_key.cst_decode(),
                address: self.address.cst_decode(),
                region: self.region.cst_decode(),
                version: self.version.cst_decode(),
                latency_ms: self.latency_ms.cst_decode(),
                is_mobile: self.is_mobile.cst_decode(),
            }
        }
    }
    impl NewWithNullPtr for wire_cst_key_pair_dto {
        fn new_with_null_ptr() -> Self {
            Self {
                public_key: core::ptr::null_mut(),
                secret_key: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_key_pair_dto {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_node_info {
        fn new_with_null_ptr() -> Self {
            Self {
                node_id: core::ptr::null_mut(),
                public_key: core::ptr::null_mut(),
                is_running: Default::default(),
            }
        }
    }
    impl Default for wire_cst_node_info {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_node_status_dto {
        fn new_with_null_ptr() -> Self {
            Self {
                is_running: Default::default(),
                node_id: core::ptr::null_mut(),
                connected_peers: Default::default(),
                discovered_peers: Default::default(),
                uptime_seconds: Default::default(),
                gossip_messages_received: Default::default(),
                storage_size_bytes: Default::default(),
                total_keys: Default::default(),
                sync_operations: Default::default(),
                latency_requests_sent: Default::default(),
                latency_responses_received: Default::default(),
            }
        }
    }
    impl Default for wire_cst_node_status_dto {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_peer_info_dto {
        fn new_with_null_ptr() -> Self {
            Self {
                node_id: core::ptr::null_mut(),
                public_key: core::ptr::null_mut(),
                address: core::ptr::null_mut(),
                region: core::ptr::null_mut(),
                version: core::ptr::null_mut(),
                latency_ms: core::ptr::null_mut(),
                is_mobile: Default::default(),
            }
        }
    }
    impl Default for wire_cst_peer_info_dto {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__extract_name_from_db(
        db_name: *mut wire_cst_list_prim_u_8_strict,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__extract_name_from_db_impl(db_name)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__generate_db_name(
        name: *mut wire_cst_list_prim_u_8_strict,
        public_key_hex: *mut wire_cst_list_prim_u_8_strict,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__generate_db_name_impl(name, public_key_hex)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__generate_keypair(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__generate_keypair_impl()
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__get_data(
        port_: i64,
        db_name: *mut wire_cst_list_prim_u_8_strict,
        key: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__get_data_impl(port_, db_name, key)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__get_node_info(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__get_node_info_impl()
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__get_node_status(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__get_node_status_impl()
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__get_peers(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__get_peers_impl()
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__greet(
        name: *mut wire_cst_list_prim_u_8_strict,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__greet_impl(name)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__init_logging(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__init_logging_impl()
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__is_node_running(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__is_node_running_impl()
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__request_sync(
        port_: i64,
        since_timestamp: *mut i64,
    ) {
        wire__crate__api__request_sync_impl(port_, since_timestamp)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__send_gossip(
        port_: i64,
        topic: *mut wire_cst_list_prim_u_8_strict,
        message: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__send_gossip_impl(port_, topic, message)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__send_latency_request(
        port_: i64,
        peer_id: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__send_latency_request_impl(port_, peer_id)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__sign_message_with_key(
        secret_key_hex: *mut wire_cst_list_prim_u_8_strict,
        message: *mut wire_cst_list_prim_u_8_strict,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__sign_message_with_key_impl(secret_key_hex, message)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__start_node(
        port_: i64,
        data_dir: *mut wire_cst_list_prim_u_8_strict,
        wallet_secret_key: *mut wire_cst_list_prim_u_8_strict,
        bootstrap_peers: *mut wire_cst_list_String,
        region: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__start_node_impl(
            port_,
            data_dir,
            wallet_secret_key,
            bootstrap_peers,
            region,
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__stop_node(port_: i64) {
        wire__crate__api__stop_node_impl(port_)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__store_data(
        port_: i64,
        db_name: *mut wire_cst_list_prim_u_8_strict,
        key: *mut wire_cst_list_prim_u_8_strict,
        value: *mut wire_cst_list_prim_u_8_loose,
        public_key: *mut wire_cst_list_prim_u_8_strict,
        signature: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__store_data_impl(port_, db_name, key, value, public_key, signature)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__store_data_local(
        port_: i64,
        db_name: *mut wire_cst_list_prim_u_8_strict,
        key: *mut wire_cst_list_prim_u_8_strict,
        value: *mut wire_cst_list_prim_u_8_loose,
    ) {
        wire__crate__api__store_data_local_impl(port_, db_name, key, value)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__validate_timestamp(
        timestamp: i64,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__validate_timestamp_impl(timestamp)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__verify_db_name(
        db_name: *mut wire_cst_list_prim_u_8_strict,
        public_key_hex: *mut wire_cst_list_prim_u_8_strict,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__verify_db_name_impl(db_name, public_key_hex)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_wire__crate__api__verify_message_signature(
        public_key_hex: *mut wire_cst_list_prim_u_8_strict,
        message: *mut wire_cst_list_prim_u_8_strict,
        signature_hex: *mut wire_cst_list_prim_u_8_strict,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__verify_message_signature_impl(public_key_hex, message, signature_hex)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_cst_new_box_autoadd_i_64(value: i64) -> *mut i64 {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_cst_new_box_autoadd_node_info(
    ) -> *mut wire_cst_node_info {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wire_cst_node_info::new_with_null_ptr())
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_cst_new_box_autoadd_u_64(value: u64) -> *mut u64 {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_cst_new_list_String(
        len: i32,
    ) -> *mut wire_cst_list_String {
        let wrap = wire_cst_list_String {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <*mut wire_cst_list_prim_u_8_strict>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_cst_new_list_peer_info_dto(
        len: i32,
    ) -> *mut wire_cst_list_peer_info_dto {
        let wrap = wire_cst_list_peer_info_dto {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <wire_cst_peer_info_dto>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_cst_new_list_prim_u_8_loose(
        len: i32,
    ) -> *mut wire_cst_list_prim_u_8_loose {
        let ans = wire_cst_list_prim_u_8_loose {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_cyberfly_mobile_node_cst_new_list_prim_u_8_strict(
        len: i32,
    ) -> *mut wire_cst_list_prim_u_8_strict {
        let ans = wire_cst_list_prim_u_8_strict {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
    }

    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_key_pair_dto {
        public_key: *mut wire_cst_list_prim_u_8_strict,
        secret_key: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_String {
        ptr: *mut *mut wire_cst_list_prim_u_8_strict,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_peer_info_dto {
        ptr: *mut wire_cst_peer_info_dto,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_prim_u_8_loose {
        ptr: *mut u8,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_prim_u_8_strict {
        ptr: *mut u8,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_node_info {
        node_id: *mut wire_cst_list_prim_u_8_strict,
        public_key: *mut wire_cst_list_prim_u_8_strict,
        is_running: bool,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_node_status_dto {
        is_running: bool,
        node_id: *mut wire_cst_list_prim_u_8_strict,
        connected_peers: u32,
        discovered_peers: u32,
        uptime_seconds: u64,
        gossip_messages_received: u64,
        storage_size_bytes: u64,
        total_keys: u64,
        sync_operations: u32,
        latency_requests_sent: u64,
        latency_responses_received: u64,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_peer_info_dto {
        node_id: *mut wire_cst_list_prim_u_8_strict,
        public_key: *mut wire_cst_list_prim_u_8_strict,
        address: *mut wire_cst_list_prim_u_8_strict,
        region: *mut wire_cst_list_prim_u_8_strict,
        version: *mut wire_cst_list_prim_u_8_strict,
        latency_ms: *mut u64,
        is_mobile: bool,
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();

    // Section: dart2rust

    impl CstDecode<String> for String {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            self
        }
    }
    impl CstDecode<crate::api::KeyPairDto>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::KeyPairDto {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                2,
                "Expected 2 elements, got {}",
                self_.length()
            );
            crate::api::KeyPairDto {
                public_key: self_.get(0).cst_decode(),
                secret_key: self_.get(1).cst_decode(),
            }
        }
    }
    impl CstDecode<Vec<String>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<String> {
            self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap()
                .iter()
                .map(CstDecode::cst_decode)
                .collect()
        }
    }
    impl CstDecode<Vec<crate::api::PeerInfoDto>>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::PeerInfoDto> {
            self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap()
                .iter()
                .map(CstDecode::cst_decode)
                .collect()
        }
    }
    impl CstDecode<Vec<u8>> for Box<[u8]> {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            self.into_vec()
        }
    }
    impl CstDecode<crate::api::NodeInfo> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::NodeInfo {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                3,
                "Expected 3 elements, got {}",
                self_.length()
            );
            crate::api::NodeInfo {
                node_id: self_.get(0).cst_decode(),
                public_key: self_.get(1).cst_decode(),
                is_running: self_.get(2).cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::NodeStatusDto>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::NodeStatusDto {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                11,
                "Expected 11 elements, got {}",
                self_.length()
            );
            crate::api::NodeStatusDto {
                is_running: self_.get(0).cst_decode(),
                node_id: self_.get(1).cst_decode(),
                connected_peers: self_.get(2).cst_decode(),
                discovered_peers: self_.get(3).cst_decode(),
                uptime_seconds: self_.get(4).cst_decode(),
                gossip_messages_received: self_.get(5).cst_decode(),
                storage_size_bytes: self_.get(6).cst_decode(),
                total_keys: self_.get(7).cst_decode(),
                sync_operations: self_.get(8).cst_decode(),
                latency_requests_sent: self_.get(9).cst_decode(),
                latency_responses_received: self_.get(10).cst_decode(),
            }
        }
    }
    impl CstDecode<Option<String>> for Option<String> {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Option<String> {
            self.map(CstDecode::cst_decode)
        }
    }
    impl CstDecode<Option<Vec<u8>>> for Option<Box<[u8]>> {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Option<Vec<u8>> {
            self.map(CstDecode::cst_decode)
        }
    }
    impl CstDecode<crate::api::PeerInfoDto>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::PeerInfoDto {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                7,
                "Expected 7 elements, got {}",
                self_.length()
            );
            crate::api::PeerInfoDto {
                node_id: self_.get(0).cst_decode(),
                public_key: self_.get(1).cst_decode(),
                address: self_.get(2).cst_decode(),
                region: self_.get(3).cst_decode(),
                version: self_.get(4).cst_decode(),
                latency_ms: self_.get(5).cst_decode(),
                is_mobile: self_.get(6).cst_decode(),
            }
        }
    }
    impl CstDecode<String> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            self.as_string().expect("non-UTF-8 string, or not a string")
        }
    }
    impl CstDecode<bool> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> bool {
            self.is_truthy()
        }
    }
    impl CstDecode<i64> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> i64 {
            ::std::convert::TryInto::<i64>::try_into(self).unwrap() as _
        }
    }
    impl CstDecode<Vec<u8>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            self.unchecked_into::<flutter_rust_bridge::for_generated::js_sys::Uint8Array>()
                .to_vec()
                .into()
        }
    }
    impl CstDecode<u32> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u32 {
            self.unchecked_into_f64() as _
        }
    }
    impl CstDecode<u64> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u64 {
            ::std::convert::TryInto::<u64>::try_into(self).unwrap() as _
        }
    }
    impl CstDecode<u8> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u8 {
            self.unchecked_into_f64() as _
        }
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__extract_name_from_db(
        db_name: String,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__extract_name_from_db_impl(db_name)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__generate_db_name(
        name: String,
        public_key_hex: String,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__generate_db_name_impl(name, public_key_hex)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__generate_keypair(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__generate_keypair_impl()
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__get_data(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        db_name: String,
        key: String,
    ) {
        wire__crate__api__get_data_impl(port_, db_name, key)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__get_node_info(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__get_node_info_impl()
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__get_node_status(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__get_node_status_impl()
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__get_peers() -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco
    {
        wire__crate__api__get_peers_impl()
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__greet(
        name: String,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__greet_impl(name)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__init_logging(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__init_logging_impl()
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__is_node_running(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__is_node_running_impl()
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__request_sync(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        since_timestamp: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    ) {
        wire__crate__api__request_sync_impl(port_, since_timestamp)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__send_gossip(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        topic: String,
        message: String,
    ) {
        wire__crate__api__send_gossip_impl(port_, topic, message)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__send_latency_request(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        peer_id: String,
    ) {
        wire__crate__api__send_latency_request_impl(port_, peer_id)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__sign_message_with_key(
        secret_key_hex: String,
        message: String,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__sign_message_with_key_impl(secret_key_hex, message)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__start_node(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        data_dir: String,
        wallet_secret_key: Option<String>,
        bootstrap_peers: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
        region: Option<String>,
    ) {
        wire__crate__api__start_node_impl(
            port_,
            data_dir,
            wallet_secret_key,
            bootstrap_peers,
            region,
        )
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__stop_node(port_: flutter_rust_bridge::for_generated::MessagePort) {
        wire__crate__api__stop_node_impl(port_)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__store_data(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        db_name: String,
        key: String,
        value: Box<[u8]>,
        public_key: String,
        signature: String,
    ) {
        wire__crate__api__store_data_impl(port_, db_name, key, value, public_key, signature)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__store_data_local(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        db_name: String,
        key: String,
        value: Box<[u8]>,
    ) {
        wire__crate__api__store_data_local_impl(port_, db_name, key, value)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__validate_timestamp(
        timestamp: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__validate_timestamp_impl(timestamp)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__verify_db_name(
        db_name: String,
        public_key_hex: String,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__verify_db_name_impl(db_name, public_key_hex)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__verify_message_signature(
        public_key_hex: String,
        message: String,
        signature_hex: String,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__verify_message_signature_impl(public_key_hex, message, signature_hex)
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;
