// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -774782195;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_cyberfly_mobile_node',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiDeleteData({
    required String dbName,
    required String key,
  });

  String? crateApiExtractNameFromDb({required String dbName});

  String crateApiGenerateDbName({
    required String name,
    required String publicKeyHex,
  });

  KeyPairDto crateApiGenerateKeypair();

  String crateApiGeneratePeerIdFromSecretKey({required String secretKeyHex});

  Future<List<DbEntryDto>> crateApiGetAllData();

  Future<List<DbEntryDto>> crateApiGetAllEntries({required String dbName});

  Future<Uint8List?> crateApiGetData({
    required String dbName,
    required String key,
  });

  NodeInfo? crateApiGetNodeInfo();

  NodeStatusDto crateApiGetNodeStatus();

  List<PeerInfoDto> crateApiGetPeers();

  String crateApiGreet({required String name});

  void crateApiInitLogging();

  bool crateApiIsNodeRunning();

  List<String> crateApiListDatabases();

  List<String> crateApiListKeys({required String dbName});

  Future<void> crateApiRequestSync({PlatformInt64? sinceTimestamp});

  Future<void> crateApiSendGossip({
    required String topic,
    required String message,
  });

  Future<void> crateApiSendLatencyRequest({required String peerId});

  String crateApiSignMessageWithKey({
    required String secretKeyHex,
    required String message,
  });

  Future<NodeInfo> crateApiStartNode({
    required String dataDir,
    String? walletSecretKey,
    required List<String> bootstrapPeers,
    String? region,
  });

  Future<void> crateApiStopNode();

  Future<void> crateApiStoreData({
    required String dbName,
    required String key,
    required List<int> value,
    required String publicKey,
    required String signature,
  });

  Future<void> crateApiStoreDataLocal({
    required String dbName,
    required String key,
    required List<int> value,
  });

  bool crateApiValidateTimestamp({required PlatformInt64 timestamp});

  bool crateApiVerifyDbName({
    required String dbName,
    required String publicKeyHex,
  });

  bool crateApiVerifyMessageSignature({
    required String publicKeyHex,
    required String message,
    required String signatureHex,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiDeleteData({
    required String dbName,
    required String key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(dbName);
          var arg1 = cst_encode_String(key);
          return wire.wire__crate__api__delete_data(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiDeleteDataConstMeta,
        argValues: [dbName, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeleteDataConstMeta => const TaskConstMeta(
    debugName: "delete_data",
    argNames: ["dbName", "key"],
  );

  @override
  String? crateApiExtractNameFromDb({required String dbName}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(dbName);
          return wire.wire__crate__api__extract_name_from_db(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiExtractNameFromDbConstMeta,
        argValues: [dbName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExtractNameFromDbConstMeta => const TaskConstMeta(
    debugName: "extract_name_from_db",
    argNames: ["dbName"],
  );

  @override
  String crateApiGenerateDbName({
    required String name,
    required String publicKeyHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(name);
          var arg1 = cst_encode_String(publicKeyHex);
          return wire.wire__crate__api__generate_db_name(arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGenerateDbNameConstMeta,
        argValues: [name, publicKeyHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateDbNameConstMeta => const TaskConstMeta(
    debugName: "generate_db_name",
    argNames: ["name", "publicKeyHex"],
  );

  @override
  KeyPairDto crateApiGenerateKeypair() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          return wire.wire__crate__api__generate_keypair();
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_key_pair_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGenerateKeypairConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateKeypairConstMeta =>
      const TaskConstMeta(debugName: "generate_keypair", argNames: []);

  @override
  String crateApiGeneratePeerIdFromSecretKey({required String secretKeyHex}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(secretKeyHex);
          return wire.wire__crate__api__generate_peer_id_from_secret_key(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiGeneratePeerIdFromSecretKeyConstMeta,
        argValues: [secretKeyHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGeneratePeerIdFromSecretKeyConstMeta =>
      const TaskConstMeta(
        debugName: "generate_peer_id_from_secret_key",
        argNames: ["secretKeyHex"],
      );

  @override
  Future<List<DbEntryDto>> crateApiGetAllData() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__get_all_data(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_db_entry_dto,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiGetAllDataConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetAllDataConstMeta =>
      const TaskConstMeta(debugName: "get_all_data", argNames: []);

  @override
  Future<List<DbEntryDto>> crateApiGetAllEntries({required String dbName}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(dbName);
          return wire.wire__crate__api__get_all_entries(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_db_entry_dto,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiGetAllEntriesConstMeta,
        argValues: [dbName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetAllEntriesConstMeta =>
      const TaskConstMeta(debugName: "get_all_entries", argNames: ["dbName"]);

  @override
  Future<Uint8List?> crateApiGetData({
    required String dbName,
    required String key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(dbName);
          var arg1 = cst_encode_String(key);
          return wire.wire__crate__api__get_data(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_list_prim_u_8_strict,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiGetDataConstMeta,
        argValues: [dbName, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetDataConstMeta =>
      const TaskConstMeta(debugName: "get_data", argNames: ["dbName", "key"]);

  @override
  NodeInfo? crateApiGetNodeInfo() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          return wire.wire__crate__api__get_node_info();
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_box_autoadd_node_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetNodeInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetNodeInfoConstMeta =>
      const TaskConstMeta(debugName: "get_node_info", argNames: []);

  @override
  NodeStatusDto crateApiGetNodeStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          return wire.wire__crate__api__get_node_status();
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_node_status_dto,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiGetNodeStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetNodeStatusConstMeta =>
      const TaskConstMeta(debugName: "get_node_status", argNames: []);

  @override
  List<PeerInfoDto> crateApiGetPeers() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          return wire.wire__crate__api__get_peers();
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_peer_info_dto,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiGetPeersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetPeersConstMeta =>
      const TaskConstMeta(debugName: "get_peers", argNames: []);

  @override
  String crateApiGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(name);
          return wire.wire__crate__api__greet(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  void crateApiInitLogging() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          return wire.wire__crate__api__init_logging();
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitLoggingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitLoggingConstMeta =>
      const TaskConstMeta(debugName: "init_logging", argNames: []);

  @override
  bool crateApiIsNodeRunning() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          return wire.wire__crate__api__is_node_running();
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIsNodeRunningConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIsNodeRunningConstMeta =>
      const TaskConstMeta(debugName: "is_node_running", argNames: []);

  @override
  List<String> crateApiListDatabases() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          return wire.wire__crate__api__list_databases();
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiListDatabasesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListDatabasesConstMeta =>
      const TaskConstMeta(debugName: "list_databases", argNames: []);

  @override
  List<String> crateApiListKeys({required String dbName}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(dbName);
          return wire.wire__crate__api__list_keys(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiListKeysConstMeta,
        argValues: [dbName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListKeysConstMeta =>
      const TaskConstMeta(debugName: "list_keys", argNames: ["dbName"]);

  @override
  Future<void> crateApiRequestSync({PlatformInt64? sinceTimestamp}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_opt_box_autoadd_i_64(sinceTimestamp);
          return wire.wire__crate__api__request_sync(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiRequestSyncConstMeta,
        argValues: [sinceTimestamp],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestSyncConstMeta => const TaskConstMeta(
    debugName: "request_sync",
    argNames: ["sinceTimestamp"],
  );

  @override
  Future<void> crateApiSendGossip({
    required String topic,
    required String message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(topic);
          var arg1 = cst_encode_String(message);
          return wire.wire__crate__api__send_gossip(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiSendGossipConstMeta,
        argValues: [topic, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendGossipConstMeta => const TaskConstMeta(
    debugName: "send_gossip",
    argNames: ["topic", "message"],
  );

  @override
  Future<void> crateApiSendLatencyRequest({required String peerId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(peerId);
          return wire.wire__crate__api__send_latency_request(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiSendLatencyRequestConstMeta,
        argValues: [peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendLatencyRequestConstMeta => const TaskConstMeta(
    debugName: "send_latency_request",
    argNames: ["peerId"],
  );

  @override
  String crateApiSignMessageWithKey({
    required String secretKeyHex,
    required String message,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(secretKeyHex);
          var arg1 = cst_encode_String(message);
          return wire.wire__crate__api__sign_message_with_key(arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiSignMessageWithKeyConstMeta,
        argValues: [secretKeyHex, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSignMessageWithKeyConstMeta => const TaskConstMeta(
    debugName: "sign_message_with_key",
    argNames: ["secretKeyHex", "message"],
  );

  @override
  Future<NodeInfo> crateApiStartNode({
    required String dataDir,
    String? walletSecretKey,
    required List<String> bootstrapPeers,
    String? region,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(dataDir);
          var arg1 = cst_encode_opt_String(walletSecretKey);
          var arg2 = cst_encode_list_String(bootstrapPeers);
          var arg3 = cst_encode_opt_String(region);
          return wire.wire__crate__api__start_node(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_node_info,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiStartNodeConstMeta,
        argValues: [dataDir, walletSecretKey, bootstrapPeers, region],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStartNodeConstMeta => const TaskConstMeta(
    debugName: "start_node",
    argNames: ["dataDir", "walletSecretKey", "bootstrapPeers", "region"],
  );

  @override
  Future<void> crateApiStopNode() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__stop_node(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiStopNodeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStopNodeConstMeta =>
      const TaskConstMeta(debugName: "stop_node", argNames: []);

  @override
  Future<void> crateApiStoreData({
    required String dbName,
    required String key,
    required List<int> value,
    required String publicKey,
    required String signature,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(dbName);
          var arg1 = cst_encode_String(key);
          var arg2 = cst_encode_list_prim_u_8_loose(value);
          var arg3 = cst_encode_String(publicKey);
          var arg4 = cst_encode_String(signature);
          return wire.wire__crate__api__store_data(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiStoreDataConstMeta,
        argValues: [dbName, key, value, publicKey, signature],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreDataConstMeta => const TaskConstMeta(
    debugName: "store_data",
    argNames: ["dbName", "key", "value", "publicKey", "signature"],
  );

  @override
  Future<void> crateApiStoreDataLocal({
    required String dbName,
    required String key,
    required List<int> value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(dbName);
          var arg1 = cst_encode_String(key);
          var arg2 = cst_encode_list_prim_u_8_loose(value);
          return wire.wire__crate__api__store_data_local(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiStoreDataLocalConstMeta,
        argValues: [dbName, key, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreDataLocalConstMeta => const TaskConstMeta(
    debugName: "store_data_local",
    argNames: ["dbName", "key", "value"],
  );

  @override
  bool crateApiValidateTimestamp({required PlatformInt64 timestamp}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_i_64(timestamp);
          return wire.wire__crate__api__validate_timestamp(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiValidateTimestampConstMeta,
        argValues: [timestamp],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiValidateTimestampConstMeta => const TaskConstMeta(
    debugName: "validate_timestamp",
    argNames: ["timestamp"],
  );

  @override
  bool crateApiVerifyDbName({
    required String dbName,
    required String publicKeyHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(dbName);
          var arg1 = cst_encode_String(publicKeyHex);
          return wire.wire__crate__api__verify_db_name(arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiVerifyDbNameConstMeta,
        argValues: [dbName, publicKeyHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVerifyDbNameConstMeta => const TaskConstMeta(
    debugName: "verify_db_name",
    argNames: ["dbName", "publicKeyHex"],
  );

  @override
  bool crateApiVerifyMessageSignature({
    required String publicKeyHex,
    required String message,
    required String signatureHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(publicKeyHex);
          var arg1 = cst_encode_String(message);
          var arg2 = cst_encode_String(signatureHex);
          return wire.wire__crate__api__verify_message_signature(
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiVerifyMessageSignatureConstMeta,
        argValues: [publicKeyHex, message, signatureHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVerifyMessageSignatureConstMeta =>
      const TaskConstMeta(
        debugName: "verify_message_signature",
        argNames: ["publicKeyHex", "message", "signatureHex"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  NodeInfo dco_decode_box_autoadd_node_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_node_info(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  DbEntryDto dco_decode_db_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DbEntryDto(
      dbName: dco_decode_String(arr[0]),
      key: dco_decode_String(arr[1]),
      value: dco_decode_String(arr[2]),
      valueBytes: dco_decode_list_prim_u_8_strict(arr[3]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  KeyPairDto dco_decode_key_pair_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return KeyPairDto(
      publicKey: dco_decode_String(arr[0]),
      secretKey: dco_decode_String(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DbEntryDto> dco_decode_list_db_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_db_entry_dto).toList();
  }

  @protected
  List<PeerInfoDto> dco_decode_list_peer_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_peer_info_dto).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  NodeInfo dco_decode_node_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NodeInfo(
      nodeId: dco_decode_String(arr[0]),
      publicKey: dco_decode_String(arr[1]),
      isRunning: dco_decode_bool(arr[2]),
    );
  }

  @protected
  NodeStatusDto dco_decode_node_status_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return NodeStatusDto(
      isRunning: dco_decode_bool(arr[0]),
      nodeId: dco_decode_opt_String(arr[1]),
      connectedPeers: dco_decode_u_32(arr[2]),
      discoveredPeers: dco_decode_u_32(arr[3]),
      uptimeSeconds: dco_decode_u_64(arr[4]),
      gossipMessagesReceived: dco_decode_u_64(arr[5]),
      storageSizeBytes: dco_decode_u_64(arr[6]),
      totalKeys: dco_decode_u_64(arr[7]),
      syncOperations: dco_decode_u_32(arr[8]),
      latencyRequestsSent: dco_decode_u_64(arr[9]),
      latencyResponsesReceived: dco_decode_u_64(arr[10]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  NodeInfo? dco_decode_opt_box_autoadd_node_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_node_info(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  PeerInfoDto dco_decode_peer_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return PeerInfoDto(
      nodeId: dco_decode_String(arr[0]),
      publicKey: dco_decode_String(arr[1]),
      address: dco_decode_opt_String(arr[2]),
      region: dco_decode_opt_String(arr[3]),
      version: dco_decode_opt_String(arr[4]),
      latencyMs: dco_decode_opt_box_autoadd_u_64(arr[5]),
      isMobile: dco_decode_bool(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  NodeInfo sse_decode_box_autoadd_node_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_node_info(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  DbEntryDto sse_decode_db_entry_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dbName = sse_decode_String(deserializer);
    var var_key = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    var var_valueBytes = sse_decode_list_prim_u_8_strict(deserializer);
    return DbEntryDto(
      dbName: var_dbName,
      key: var_key,
      value: var_value,
      valueBytes: var_valueBytes,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  KeyPairDto sse_decode_key_pair_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_publicKey = sse_decode_String(deserializer);
    var var_secretKey = sse_decode_String(deserializer);
    return KeyPairDto(publicKey: var_publicKey, secretKey: var_secretKey);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DbEntryDto> sse_decode_list_db_entry_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DbEntryDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_db_entry_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<PeerInfoDto> sse_decode_list_peer_info_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PeerInfoDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_peer_info_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  NodeInfo sse_decode_node_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodeId = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_String(deserializer);
    var var_isRunning = sse_decode_bool(deserializer);
    return NodeInfo(
      nodeId: var_nodeId,
      publicKey: var_publicKey,
      isRunning: var_isRunning,
    );
  }

  @protected
  NodeStatusDto sse_decode_node_status_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isRunning = sse_decode_bool(deserializer);
    var var_nodeId = sse_decode_opt_String(deserializer);
    var var_connectedPeers = sse_decode_u_32(deserializer);
    var var_discoveredPeers = sse_decode_u_32(deserializer);
    var var_uptimeSeconds = sse_decode_u_64(deserializer);
    var var_gossipMessagesReceived = sse_decode_u_64(deserializer);
    var var_storageSizeBytes = sse_decode_u_64(deserializer);
    var var_totalKeys = sse_decode_u_64(deserializer);
    var var_syncOperations = sse_decode_u_32(deserializer);
    var var_latencyRequestsSent = sse_decode_u_64(deserializer);
    var var_latencyResponsesReceived = sse_decode_u_64(deserializer);
    return NodeStatusDto(
      isRunning: var_isRunning,
      nodeId: var_nodeId,
      connectedPeers: var_connectedPeers,
      discoveredPeers: var_discoveredPeers,
      uptimeSeconds: var_uptimeSeconds,
      gossipMessagesReceived: var_gossipMessagesReceived,
      storageSizeBytes: var_storageSizeBytes,
      totalKeys: var_totalKeys,
      syncOperations: var_syncOperations,
      latencyRequestsSent: var_latencyRequestsSent,
      latencyResponsesReceived: var_latencyResponsesReceived,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  NodeInfo? sse_decode_opt_box_autoadd_node_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_node_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PeerInfoDto sse_decode_peer_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodeId = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_String(deserializer);
    var var_address = sse_decode_opt_String(deserializer);
    var var_region = sse_decode_opt_String(deserializer);
    var var_version = sse_decode_opt_String(deserializer);
    var var_latencyMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_isMobile = sse_decode_bool(deserializer);
    return PeerInfoDto(
      nodeId: var_nodeId,
      publicKey: var_publicKey,
      address: var_address,
      region: var_region,
      version: var_version,
      latencyMs: var_latencyMs,
      isMobile: var_isMobile,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_node_info(
    NodeInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_node_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_db_entry_dto(DbEntryDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.dbName, serializer);
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.value, serializer);
    sse_encode_list_prim_u_8_strict(self.valueBytes, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_key_pair_dto(KeyPairDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.publicKey, serializer);
    sse_encode_String(self.secretKey, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_db_entry_dto(
    List<DbEntryDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_db_entry_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_peer_info_dto(
    List<PeerInfoDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_peer_info_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_node_info(NodeInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nodeId, serializer);
    sse_encode_String(self.publicKey, serializer);
    sse_encode_bool(self.isRunning, serializer);
  }

  @protected
  void sse_encode_node_status_dto(
    NodeStatusDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isRunning, serializer);
    sse_encode_opt_String(self.nodeId, serializer);
    sse_encode_u_32(self.connectedPeers, serializer);
    sse_encode_u_32(self.discoveredPeers, serializer);
    sse_encode_u_64(self.uptimeSeconds, serializer);
    sse_encode_u_64(self.gossipMessagesReceived, serializer);
    sse_encode_u_64(self.storageSizeBytes, serializer);
    sse_encode_u_64(self.totalKeys, serializer);
    sse_encode_u_32(self.syncOperations, serializer);
    sse_encode_u_64(self.latencyRequestsSent, serializer);
    sse_encode_u_64(self.latencyResponsesReceived, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_node_info(
    NodeInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_node_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_peer_info_dto(PeerInfoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nodeId, serializer);
    sse_encode_String(self.publicKey, serializer);
    sse_encode_opt_String(self.address, serializer);
    sse_encode_opt_String(self.region, serializer);
    sse_encode_opt_String(self.version, serializer);
    sse_encode_opt_box_autoadd_u_64(self.latencyMs, serializer);
    sse_encode_bool(self.isMobile, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
