// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  NodeInfo dco_decode_box_autoadd_node_info(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  DbEntryDto dco_decode_db_entry_dto(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  KeyPairDto dco_decode_key_pair_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DbEntryDto> dco_decode_list_db_entry_dto(dynamic raw);

  @protected
  List<PeerInfoDto> dco_decode_list_peer_info_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  NodeInfo dco_decode_node_info(dynamic raw);

  @protected
  NodeStatusDto dco_decode_node_status_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  NodeInfo? dco_decode_opt_box_autoadd_node_info(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PeerInfoDto dco_decode_peer_info_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  NodeInfo sse_decode_box_autoadd_node_info(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  DbEntryDto sse_decode_db_entry_dto(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  KeyPairDto sse_decode_key_pair_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DbEntryDto> sse_decode_list_db_entry_dto(SseDeserializer deserializer);

  @protected
  List<PeerInfoDto> sse_decode_list_peer_info_dto(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  NodeInfo sse_decode_node_info(SseDeserializer deserializer);

  @protected
  NodeStatusDto sse_decode_node_status_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  NodeInfo? sse_decode_opt_box_autoadd_node_info(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PeerInfoDto sse_decode_peer_info_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_box_autoadd_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_64(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_node_info(NodeInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_node_info(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_u_64(raw);
  }

  @protected
  JSAny cst_encode_db_entry_dto(DbEntryDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.dbName),
      cst_encode_String(raw.key),
      cst_encode_String(raw.value),
      cst_encode_list_prim_u_8_strict(raw.valueBytes),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_key_pair_dto(KeyPairDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.publicKey),
      cst_encode_String(raw.secretKey),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_String).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_db_entry_dto(List<DbEntryDto> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_db_entry_dto).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_peer_info_dto(List<PeerInfoDto> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_peer_info_dto).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_loose(List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_node_info(NodeInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.nodeId),
      cst_encode_String(raw.publicKey),
      cst_encode_bool(raw.isRunning),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_node_status_dto(NodeStatusDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.isRunning),
      cst_encode_opt_String(raw.nodeId),
      cst_encode_u_32(raw.connectedPeers),
      cst_encode_u_32(raw.discoveredPeers),
      cst_encode_u_64(raw.uptimeSeconds),
      cst_encode_u_64(raw.gossipMessagesReceived),
      cst_encode_u_64(raw.storageSizeBytes),
      cst_encode_u_64(raw.totalKeys),
      cst_encode_u_32(raw.syncOperations),
      cst_encode_u_64(raw.latencyRequestsSent),
      cst_encode_u_64(raw.latencyResponsesReceived),
    ].jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_i_64(PlatformInt64? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_i_64(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_node_info(NodeInfo? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_node_info(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_u_64(BigInt? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_u_64(raw);
  }

  @protected
  JSAny? cst_encode_opt_list_prim_u_8_strict(Uint8List? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_list_prim_u_8_strict(raw);
  }

  @protected
  JSAny cst_encode_peer_info_dto(PeerInfoDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.nodeId),
      cst_encode_String(raw.publicKey),
      cst_encode_opt_String(raw.address),
      cst_encode_opt_String(raw.region),
      cst_encode_opt_String(raw.version),
      cst_encode_opt_box_autoadd_u_64(raw.latencyMs),
      cst_encode_bool(raw.isMobile),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_node_info(
    NodeInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_db_entry_dto(DbEntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_key_pair_dto(KeyPairDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_db_entry_dto(
    List<DbEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_peer_info_dto(
    List<PeerInfoDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_node_info(NodeInfo self, SseSerializer serializer);

  @protected
  void sse_encode_node_status_dto(NodeStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_node_info(
    NodeInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_peer_info_dto(PeerInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__delete_data(
    NativePortType port_,
    String db_name,
    String key,
  ) => wasmModule.wire__crate__api__delete_data(port_, db_name, key);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__extract_name_from_db(String db_name) =>
      wasmModule.wire__crate__api__extract_name_from_db(db_name);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__generate_db_name(String name, String public_key_hex) =>
      wasmModule.wire__crate__api__generate_db_name(name, public_key_hex);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__generate_keypair() =>
      wasmModule.wire__crate__api__generate_keypair();

  void wire__crate__api__get_all_data(NativePortType port_) =>
      wasmModule.wire__crate__api__get_all_data(port_);

  void wire__crate__api__get_all_entries(
    NativePortType port_,
    String db_name,
  ) => wasmModule.wire__crate__api__get_all_entries(port_, db_name);

  void wire__crate__api__get_data(
    NativePortType port_,
    String db_name,
    String key,
  ) => wasmModule.wire__crate__api__get_data(port_, db_name, key);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__get_node_info() =>
      wasmModule.wire__crate__api__get_node_info();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__get_node_status() =>
      wasmModule.wire__crate__api__get_node_status();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__get_peers() => wasmModule.wire__crate__api__get_peers();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__greet(String name) =>
      wasmModule.wire__crate__api__greet(name);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__init_logging() =>
      wasmModule.wire__crate__api__init_logging();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__is_node_running() =>
      wasmModule.wire__crate__api__is_node_running();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__list_databases() =>
      wasmModule.wire__crate__api__list_databases();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__list_keys(String db_name) =>
      wasmModule.wire__crate__api__list_keys(db_name);

  void wire__crate__api__request_sync(
    NativePortType port_,
    JSAny? since_timestamp,
  ) => wasmModule.wire__crate__api__request_sync(port_, since_timestamp);

  void wire__crate__api__send_gossip(
    NativePortType port_,
    String topic,
    String message,
  ) => wasmModule.wire__crate__api__send_gossip(port_, topic, message);

  void wire__crate__api__send_latency_request(
    NativePortType port_,
    String peer_id,
  ) => wasmModule.wire__crate__api__send_latency_request(port_, peer_id);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__sign_message_with_key(
    String secret_key_hex,
    String message,
  ) => wasmModule.wire__crate__api__sign_message_with_key(
    secret_key_hex,
    message,
  );

  void wire__crate__api__start_node(
    NativePortType port_,
    String data_dir,
    String? wallet_secret_key,
    JSAny bootstrap_peers,
    String? region,
  ) => wasmModule.wire__crate__api__start_node(
    port_,
    data_dir,
    wallet_secret_key,
    bootstrap_peers,
    region,
  );

  void wire__crate__api__stop_node(NativePortType port_) =>
      wasmModule.wire__crate__api__stop_node(port_);

  void wire__crate__api__store_data(
    NativePortType port_,
    String db_name,
    String key,
    JSAny value,
    String public_key,
    String signature,
  ) => wasmModule.wire__crate__api__store_data(
    port_,
    db_name,
    key,
    value,
    public_key,
    signature,
  );

  void wire__crate__api__store_data_local(
    NativePortType port_,
    String db_name,
    String key,
    JSAny value,
  ) =>
      wasmModule.wire__crate__api__store_data_local(port_, db_name, key, value);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__validate_timestamp(JSAny timestamp) =>
      wasmModule.wire__crate__api__validate_timestamp(timestamp);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__verify_db_name(String db_name, String public_key_hex) =>
      wasmModule.wire__crate__api__verify_db_name(db_name, public_key_hex);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__verify_message_signature(
    String public_key_hex,
    String message,
    String signature_hex,
  ) => wasmModule.wire__crate__api__verify_message_signature(
    public_key_hex,
    message,
    signature_hex,
  );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__delete_data(
    NativePortType port_,
    String db_name,
    String key,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__extract_name_from_db(String db_name);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__generate_db_name(String name, String public_key_hex);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__generate_keypair();

  external void wire__crate__api__get_all_data(NativePortType port_);

  external void wire__crate__api__get_all_entries(
    NativePortType port_,
    String db_name,
  );

  external void wire__crate__api__get_data(
    NativePortType port_,
    String db_name,
    String key,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__get_node_info();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__get_node_status();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__get_peers();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__greet(String name);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__init_logging();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__is_node_running();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__list_databases();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__list_keys(String db_name);

  external void wire__crate__api__request_sync(
    NativePortType port_,
    JSAny? since_timestamp,
  );

  external void wire__crate__api__send_gossip(
    NativePortType port_,
    String topic,
    String message,
  );

  external void wire__crate__api__send_latency_request(
    NativePortType port_,
    String peer_id,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__sign_message_with_key(
    String secret_key_hex,
    String message,
  );

  external void wire__crate__api__start_node(
    NativePortType port_,
    String data_dir,
    String? wallet_secret_key,
    JSAny bootstrap_peers,
    String? region,
  );

  external void wire__crate__api__stop_node(NativePortType port_);

  external void wire__crate__api__store_data(
    NativePortType port_,
    String db_name,
    String key,
    JSAny value,
    String public_key,
    String signature,
  );

  external void wire__crate__api__store_data_local(
    NativePortType port_,
    String db_name,
    String key,
    JSAny value,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__validate_timestamp(JSAny timestamp);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__verify_db_name(String db_name, String public_key_hex);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__verify_message_signature(
    String public_key_hex,
    String message,
    String signature_hex,
  );
}
