// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  NodeInfo dco_decode_box_autoadd_node_info(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  DbEntryDto dco_decode_db_entry_dto(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  KeyPairDto dco_decode_key_pair_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DbEntryDto> dco_decode_list_db_entry_dto(dynamic raw);

  @protected
  List<PeerInfoDto> dco_decode_list_peer_info_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  NodeInfo dco_decode_node_info(dynamic raw);

  @protected
  NodeStatusDto dco_decode_node_status_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  NodeInfo? dco_decode_opt_box_autoadd_node_info(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PeerInfoDto dco_decode_peer_info_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  NodeInfo sse_decode_box_autoadd_node_info(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  DbEntryDto sse_decode_db_entry_dto(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  KeyPairDto sse_decode_key_pair_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DbEntryDto> sse_decode_list_db_entry_dto(SseDeserializer deserializer);

  @protected
  List<PeerInfoDto> sse_decode_list_peer_info_dto(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  NodeInfo sse_decode_node_info(SseDeserializer deserializer);

  @protected
  NodeStatusDto sse_decode_node_status_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  NodeInfo? sse_decode_opt_box_autoadd_node_info(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PeerInfoDto sse_decode_peer_info_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_box_autoadd_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_i_64(cst_encode_i_64(raw));
  }

  @protected
  ffi.Pointer<wire_cst_node_info> cst_encode_box_autoadd_node_info(
    NodeInfo raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_node_info();
    cst_api_fill_to_wire_node_info(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<ffi.Uint64> cst_encode_box_autoadd_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_u_64(cst_encode_u_64(raw));
  }

  @protected
  int cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toInt();
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_String(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_db_entry_dto> cst_encode_list_db_entry_dto(
    List<DbEntryDto> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_db_entry_dto(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_db_entry_dto(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_peer_info_dto> cst_encode_list_peer_info_dto(
    List<PeerInfoDto> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_peer_info_dto(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_peer_info_dto(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_encode_list_prim_u_8_loose(
    List<int> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
    String? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_opt_box_autoadd_i_64(PlatformInt64? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_i_64(raw);
  }

  @protected
  ffi.Pointer<wire_cst_node_info> cst_encode_opt_box_autoadd_node_info(
    NodeInfo? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_node_info(raw);
  }

  @protected
  ffi.Pointer<ffi.Uint64> cst_encode_opt_box_autoadd_u_64(BigInt? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_u_64(raw);
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict>
  cst_encode_opt_list_prim_u_8_strict(Uint8List? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_list_prim_u_8_strict(raw);
  }

  @protected
  int cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_node_info(
    NodeInfo apiObj,
    ffi.Pointer<wire_cst_node_info> wireObj,
  ) {
    cst_api_fill_to_wire_node_info(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_db_entry_dto(
    DbEntryDto apiObj,
    wire_cst_db_entry_dto wireObj,
  ) {
    wireObj.db_name = cst_encode_String(apiObj.dbName);
    wireObj.key = cst_encode_String(apiObj.key);
    wireObj.value = cst_encode_String(apiObj.value);
    wireObj.value_bytes = cst_encode_list_prim_u_8_strict(apiObj.valueBytes);
  }

  @protected
  void cst_api_fill_to_wire_key_pair_dto(
    KeyPairDto apiObj,
    wire_cst_key_pair_dto wireObj,
  ) {
    wireObj.public_key = cst_encode_String(apiObj.publicKey);
    wireObj.secret_key = cst_encode_String(apiObj.secretKey);
  }

  @protected
  void cst_api_fill_to_wire_node_info(
    NodeInfo apiObj,
    wire_cst_node_info wireObj,
  ) {
    wireObj.node_id = cst_encode_String(apiObj.nodeId);
    wireObj.public_key = cst_encode_String(apiObj.publicKey);
    wireObj.is_running = cst_encode_bool(apiObj.isRunning);
  }

  @protected
  void cst_api_fill_to_wire_node_status_dto(
    NodeStatusDto apiObj,
    wire_cst_node_status_dto wireObj,
  ) {
    wireObj.is_running = cst_encode_bool(apiObj.isRunning);
    wireObj.node_id = cst_encode_opt_String(apiObj.nodeId);
    wireObj.connected_peers = cst_encode_u_32(apiObj.connectedPeers);
    wireObj.discovered_peers = cst_encode_u_32(apiObj.discoveredPeers);
    wireObj.uptime_seconds = cst_encode_u_64(apiObj.uptimeSeconds);
    wireObj.gossip_messages_received = cst_encode_u_64(
      apiObj.gossipMessagesReceived,
    );
    wireObj.storage_size_bytes = cst_encode_u_64(apiObj.storageSizeBytes);
    wireObj.total_keys = cst_encode_u_64(apiObj.totalKeys);
    wireObj.sync_operations = cst_encode_u_32(apiObj.syncOperations);
    wireObj.latency_requests_sent = cst_encode_u_64(apiObj.latencyRequestsSent);
    wireObj.latency_responses_received = cst_encode_u_64(
      apiObj.latencyResponsesReceived,
    );
  }

  @protected
  void cst_api_fill_to_wire_peer_info_dto(
    PeerInfoDto apiObj,
    wire_cst_peer_info_dto wireObj,
  ) {
    wireObj.node_id = cst_encode_String(apiObj.nodeId);
    wireObj.public_key = cst_encode_String(apiObj.publicKey);
    wireObj.address = cst_encode_opt_String(apiObj.address);
    wireObj.region = cst_encode_opt_String(apiObj.region);
    wireObj.version = cst_encode_opt_String(apiObj.version);
    wireObj.latency_ms = cst_encode_opt_box_autoadd_u_64(apiObj.latencyMs);
    wireObj.is_mobile = cst_encode_bool(apiObj.isMobile);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_node_info(
    NodeInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_db_entry_dto(DbEntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_key_pair_dto(KeyPairDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_db_entry_dto(
    List<DbEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_peer_info_dto(
    List<PeerInfoDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_node_info(NodeInfo self, SseSerializer serializer);

  @protected
  void sse_encode_node_status_dto(NodeStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_node_info(
    NodeInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_peer_info_dto(PeerInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__delete_data(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> db_name,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> key,
  ) {
    return _wire__crate__api__delete_data(port_, db_name, key);
  }

  late final _wire__crate__api__delete_dataPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_cyberfly_mobile_node_wire__crate__api__delete_data');
  late final _wire__crate__api__delete_data = _wire__crate__api__delete_dataPtr
      .asFunction<
        void Function(
          int,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        )
      >();

  WireSyncRust2DartDco wire__crate__api__extract_name_from_db(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> db_name,
  ) {
    return _wire__crate__api__extract_name_from_db(db_name);
  }

  late final _wire__crate__api__extract_name_from_dbPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_cyberfly_mobile_node_wire__crate__api__extract_name_from_db');
  late final _wire__crate__api__extract_name_from_db =
      _wire__crate__api__extract_name_from_dbPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__generate_db_name(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> name,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key_hex,
  ) {
    return _wire__crate__api__generate_db_name(name, public_key_hex);
  }

  late final _wire__crate__api__generate_db_namePtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_cyberfly_mobile_node_wire__crate__api__generate_db_name');
  late final _wire__crate__api__generate_db_name =
      _wire__crate__api__generate_db_namePtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__generate_keypair() {
    return _wire__crate__api__generate_keypair();
  }

  late final _wire__crate__api__generate_keypairPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_cyberfly_mobile_node_wire__crate__api__generate_keypair',
      );
  late final _wire__crate__api__generate_keypair =
      _wire__crate__api__generate_keypairPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__generate_peer_id_from_secret_key(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> secret_key_hex,
  ) {
    return _wire__crate__api__generate_peer_id_from_secret_key(secret_key_hex);
  }

  late final _wire__crate__api__generate_peer_id_from_secret_keyPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_cyberfly_mobile_node_wire__crate__api__generate_peer_id_from_secret_key',
      );
  late final _wire__crate__api__generate_peer_id_from_secret_key =
      _wire__crate__api__generate_peer_id_from_secret_keyPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__get_all_data(int port_) {
    return _wire__crate__api__get_all_data(port_);
  }

  late final _wire__crate__api__get_all_dataPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_cyberfly_mobile_node_wire__crate__api__get_all_data',
      );
  late final _wire__crate__api__get_all_data =
      _wire__crate__api__get_all_dataPtr.asFunction<void Function(int)>();

  void wire__crate__api__get_all_entries(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> db_name,
  ) {
    return _wire__crate__api__get_all_entries(port_, db_name);
  }

  late final _wire__crate__api__get_all_entriesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_cyberfly_mobile_node_wire__crate__api__get_all_entries');
  late final _wire__crate__api__get_all_entries =
      _wire__crate__api__get_all_entriesPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__get_data(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> db_name,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> key,
  ) {
    return _wire__crate__api__get_data(port_, db_name, key);
  }

  late final _wire__crate__api__get_dataPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_cyberfly_mobile_node_wire__crate__api__get_data');
  late final _wire__crate__api__get_data = _wire__crate__api__get_dataPtr
      .asFunction<
        void Function(
          int,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        )
      >();

  WireSyncRust2DartDco wire__crate__api__get_node_info() {
    return _wire__crate__api__get_node_info();
  }

  late final _wire__crate__api__get_node_infoPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_cyberfly_mobile_node_wire__crate__api__get_node_info',
      );
  late final _wire__crate__api__get_node_info =
      _wire__crate__api__get_node_infoPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__get_node_status() {
    return _wire__crate__api__get_node_status();
  }

  late final _wire__crate__api__get_node_statusPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_cyberfly_mobile_node_wire__crate__api__get_node_status',
      );
  late final _wire__crate__api__get_node_status =
      _wire__crate__api__get_node_statusPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__get_peers() {
    return _wire__crate__api__get_peers();
  }

  late final _wire__crate__api__get_peersPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_cyberfly_mobile_node_wire__crate__api__get_peers',
      );
  late final _wire__crate__api__get_peers = _wire__crate__api__get_peersPtr
      .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__greet(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> name,
  ) {
    return _wire__crate__api__greet(name);
  }

  late final _wire__crate__api__greetPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_cyberfly_mobile_node_wire__crate__api__greet');
  late final _wire__crate__api__greet = _wire__crate__api__greetPtr
      .asFunction<
        WireSyncRust2DartDco Function(
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        )
      >();

  WireSyncRust2DartDco wire__crate__api__init_logging() {
    return _wire__crate__api__init_logging();
  }

  late final _wire__crate__api__init_loggingPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_cyberfly_mobile_node_wire__crate__api__init_logging',
      );
  late final _wire__crate__api__init_logging =
      _wire__crate__api__init_loggingPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__is_node_running() {
    return _wire__crate__api__is_node_running();
  }

  late final _wire__crate__api__is_node_runningPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_cyberfly_mobile_node_wire__crate__api__is_node_running',
      );
  late final _wire__crate__api__is_node_running =
      _wire__crate__api__is_node_runningPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__list_databases() {
    return _wire__crate__api__list_databases();
  }

  late final _wire__crate__api__list_databasesPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_cyberfly_mobile_node_wire__crate__api__list_databases',
      );
  late final _wire__crate__api__list_databases =
      _wire__crate__api__list_databasesPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__list_keys(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> db_name,
  ) {
    return _wire__crate__api__list_keys(db_name);
  }

  late final _wire__crate__api__list_keysPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_cyberfly_mobile_node_wire__crate__api__list_keys');
  late final _wire__crate__api__list_keys = _wire__crate__api__list_keysPtr
      .asFunction<
        WireSyncRust2DartDco Function(
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        )
      >();

  void wire__crate__api__request_sync(
    int port_,
    ffi.Pointer<ffi.Int64> since_timestamp,
  ) {
    return _wire__crate__api__request_sync(port_, since_timestamp);
  }

  late final _wire__crate__api__request_syncPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Int64>)>
      >('frbgen_cyberfly_mobile_node_wire__crate__api__request_sync');
  late final _wire__crate__api__request_sync =
      _wire__crate__api__request_syncPtr
          .asFunction<void Function(int, ffi.Pointer<ffi.Int64>)>();

  void wire__crate__api__send_gossip(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> topic,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> message,
  ) {
    return _wire__crate__api__send_gossip(port_, topic, message);
  }

  late final _wire__crate__api__send_gossipPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_cyberfly_mobile_node_wire__crate__api__send_gossip');
  late final _wire__crate__api__send_gossip = _wire__crate__api__send_gossipPtr
      .asFunction<
        void Function(
          int,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        )
      >();

  void wire__crate__api__send_latency_request(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> peer_id,
  ) {
    return _wire__crate__api__send_latency_request(port_, peer_id);
  }

  late final _wire__crate__api__send_latency_requestPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_cyberfly_mobile_node_wire__crate__api__send_latency_request');
  late final _wire__crate__api__send_latency_request =
      _wire__crate__api__send_latency_requestPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  WireSyncRust2DartDco wire__crate__api__sign_message_with_key(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> secret_key_hex,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> message,
  ) {
    return _wire__crate__api__sign_message_with_key(secret_key_hex, message);
  }

  late final _wire__crate__api__sign_message_with_keyPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_cyberfly_mobile_node_wire__crate__api__sign_message_with_key');
  late final _wire__crate__api__sign_message_with_key =
      _wire__crate__api__sign_message_with_keyPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__start_node(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> data_dir,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> wallet_secret_key,
    ffi.Pointer<wire_cst_list_String> bootstrap_peers,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> region,
  ) {
    return _wire__crate__api__start_node(
      port_,
      data_dir,
      wallet_secret_key,
      bootstrap_peers,
      region,
    );
  }

  late final _wire__crate__api__start_nodePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_String>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_cyberfly_mobile_node_wire__crate__api__start_node');
  late final _wire__crate__api__start_node = _wire__crate__api__start_nodePtr
      .asFunction<
        void Function(
          int,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_String>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        )
      >();

  void wire__crate__api__stop_node(int port_) {
    return _wire__crate__api__stop_node(port_);
  }

  late final _wire__crate__api__stop_nodePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_cyberfly_mobile_node_wire__crate__api__stop_node',
      );
  late final _wire__crate__api__stop_node = _wire__crate__api__stop_nodePtr
      .asFunction<void Function(int)>();

  void wire__crate__api__store_data(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> db_name,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> key,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> value,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> signature,
  ) {
    return _wire__crate__api__store_data(
      port_,
      db_name,
      key,
      value,
      public_key,
      signature,
    );
  }

  late final _wire__crate__api__store_dataPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_cyberfly_mobile_node_wire__crate__api__store_data');
  late final _wire__crate__api__store_data = _wire__crate__api__store_dataPtr
      .asFunction<
        void Function(
          int,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        )
      >();

  void wire__crate__api__store_data_local(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> db_name,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> key,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> value,
  ) {
    return _wire__crate__api__store_data_local(port_, db_name, key, value);
  }

  late final _wire__crate__api__store_data_localPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_cyberfly_mobile_node_wire__crate__api__store_data_local');
  late final _wire__crate__api__store_data_local =
      _wire__crate__api__store_data_localPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__validate_timestamp(int timestamp) {
    return _wire__crate__api__validate_timestamp(timestamp);
  }

  late final _wire__crate__api__validate_timestampPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.Int64)>>(
        'frbgen_cyberfly_mobile_node_wire__crate__api__validate_timestamp',
      );
  late final _wire__crate__api__validate_timestamp =
      _wire__crate__api__validate_timestampPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco wire__crate__api__verify_db_name(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> db_name,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key_hex,
  ) {
    return _wire__crate__api__verify_db_name(db_name, public_key_hex);
  }

  late final _wire__crate__api__verify_db_namePtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_cyberfly_mobile_node_wire__crate__api__verify_db_name');
  late final _wire__crate__api__verify_db_name =
      _wire__crate__api__verify_db_namePtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__verify_message_signature(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key_hex,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> message,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> signature_hex,
  ) {
    return _wire__crate__api__verify_message_signature(
      public_key_hex,
      message,
      signature_hex,
    );
  }

  late final _wire__crate__api__verify_message_signaturePtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >(
        'frbgen_cyberfly_mobile_node_wire__crate__api__verify_message_signature',
      );
  late final _wire__crate__api__verify_message_signature =
      _wire__crate__api__verify_message_signaturePtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  ffi.Pointer<ffi.Int64> cst_new_box_autoadd_i_64(int value) {
    return _cst_new_box_autoadd_i_64(value);
  }

  late final _cst_new_box_autoadd_i_64Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int64> Function(ffi.Int64)>>(
        'frbgen_cyberfly_mobile_node_cst_new_box_autoadd_i_64',
      );
  late final _cst_new_box_autoadd_i_64 = _cst_new_box_autoadd_i_64Ptr
      .asFunction<ffi.Pointer<ffi.Int64> Function(int)>();

  ffi.Pointer<wire_cst_node_info> cst_new_box_autoadd_node_info() {
    return _cst_new_box_autoadd_node_info();
  }

  late final _cst_new_box_autoadd_node_infoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_node_info> Function()>>(
        'frbgen_cyberfly_mobile_node_cst_new_box_autoadd_node_info',
      );
  late final _cst_new_box_autoadd_node_info = _cst_new_box_autoadd_node_infoPtr
      .asFunction<ffi.Pointer<wire_cst_node_info> Function()>();

  ffi.Pointer<ffi.Uint64> cst_new_box_autoadd_u_64(int value) {
    return _cst_new_box_autoadd_u_64(value);
  }

  late final _cst_new_box_autoadd_u_64Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Uint64> Function(ffi.Uint64)>>(
        'frbgen_cyberfly_mobile_node_cst_new_box_autoadd_u_64',
      );
  late final _cst_new_box_autoadd_u_64 = _cst_new_box_autoadd_u_64Ptr
      .asFunction<ffi.Pointer<ffi.Uint64> Function(int)>();

  ffi.Pointer<wire_cst_list_String> cst_new_list_String(int len) {
    return _cst_new_list_String(len);
  }

  late final _cst_new_list_StringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_String> Function(ffi.Int32)
        >
      >('frbgen_cyberfly_mobile_node_cst_new_list_String');
  late final _cst_new_list_String = _cst_new_list_StringPtr
      .asFunction<ffi.Pointer<wire_cst_list_String> Function(int)>();

  ffi.Pointer<wire_cst_list_db_entry_dto> cst_new_list_db_entry_dto(int len) {
    return _cst_new_list_db_entry_dto(len);
  }

  late final _cst_new_list_db_entry_dtoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_db_entry_dto> Function(ffi.Int32)
        >
      >('frbgen_cyberfly_mobile_node_cst_new_list_db_entry_dto');
  late final _cst_new_list_db_entry_dto = _cst_new_list_db_entry_dtoPtr
      .asFunction<ffi.Pointer<wire_cst_list_db_entry_dto> Function(int)>();

  ffi.Pointer<wire_cst_list_peer_info_dto> cst_new_list_peer_info_dto(int len) {
    return _cst_new_list_peer_info_dto(len);
  }

  late final _cst_new_list_peer_info_dtoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_peer_info_dto> Function(ffi.Int32)
        >
      >('frbgen_cyberfly_mobile_node_cst_new_list_peer_info_dto');
  late final _cst_new_list_peer_info_dto = _cst_new_list_peer_info_dtoPtr
      .asFunction<ffi.Pointer<wire_cst_list_peer_info_dto> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_new_list_prim_u_8_loose(
    int len,
  ) {
    return _cst_new_list_prim_u_8_loose(len);
  }

  late final _cst_new_list_prim_u_8_loosePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(ffi.Int32)
        >
      >('frbgen_cyberfly_mobile_node_cst_new_list_prim_u_8_loose');
  late final _cst_new_list_prim_u_8_loose = _cst_new_list_prim_u_8_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_cyberfly_mobile_node_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnTypeFunction =
    ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction =
    bool Function(DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPostCObjectFnType =
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_String extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_u_8_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_node_info extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> node_id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key;

  @ffi.Bool()
  external bool is_running;
}

final class wire_cst_db_entry_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> db_name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> key;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> value;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> value_bytes;
}

final class wire_cst_list_db_entry_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_db_entry_dto> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_peer_info_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> node_id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> address;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> region;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> version;

  external ffi.Pointer<ffi.Uint64> latency_ms;

  @ffi.Bool()
  external bool is_mobile;
}

final class wire_cst_list_peer_info_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_peer_info_dto> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_key_pair_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> public_key;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> secret_key;
}

final class wire_cst_node_status_dto extends ffi.Struct {
  @ffi.Bool()
  external bool is_running;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> node_id;

  @ffi.Uint32()
  external int connected_peers;

  @ffi.Uint32()
  external int discovered_peers;

  @ffi.Uint64()
  external int uptime_seconds;

  @ffi.Uint64()
  external int gossip_messages_received;

  @ffi.Uint64()
  external int storage_size_bytes;

  @ffi.Uint64()
  external int total_keys;

  @ffi.Uint32()
  external int sync_operations;

  @ffi.Uint64()
  external int latency_requests_sent;

  @ffi.Uint64()
  external int latency_responses_received;
}

const int ED25519_PUBLIC_KEY_LENGTH = 32;

const int ED25519_SIGNATURE_LENGTH = 64;

const int MAX_MESSAGE_LENGTH = 1048576;

const int MIN_TIMESTAMP_TOLERANCE = 300;

const int MAX_TIMESTAMP_TOLERANCE = 3600;

const int PEER_EXPIRY_SECS = 300;

const int ANNOUNCE_INTERVAL_SECS = 10;
