import 'dart:ffi';
import 'dart:io';

/// This is a helper library for loading the Rust native library.
/// The actual FFI bindings are generated by flutter_rust_bridge.
library rust_lib;

const _libName = 'rust_lib_cyberfly_mobile_node';

/// The dynamic library in which the symbols for [RustLibApi] can be found.
final DynamicLibrary dylib = () {
  if (Platform.isIOS || Platform.isMacOS) {
    return DynamicLibrary.open('$_libName.framework/$_libName');
  }
  if (Platform.isAndroid || Platform.isLinux) {
    return DynamicLibrary.open('lib$_libName.so');
  }
  if (Platform.isWindows) {
    return DynamicLibrary.open('$_libName.dll');
  }
  throw UnsupportedError('Unknown platform: ${Platform.operatingSystem}');
}();
